language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
before_install:
  - gem update --system
  - gem update bundler
gemfile:
  - gemfiles/3.0.17.gemfile
  - gemfiles/3.1.8.gemfile
  - gemfiles/3.2.8.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/3.0.17.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/3.1.8.gemfile
branches:
  only:
    - master
